name: Qlty Coverage

on:
  push:
    branches: [ "master" ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install jest for CI only
        run: npm install --save-dev jest @types/jest ts-jest

      - name: Run coverage
        run: npx jest --coverage

      - name: Upload coverage to qlty.sh
        uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/lcov.info